### PR TITLE
Do not error if last reserved not found after initial creation

### PR DESCRIPTION
**Pull request by ehazlett**
When using the `host-local` IPAM plugin, after initial network creation the following error is printed due to missing file:

```
2017/02/03 17:50:08 Error retriving last reserved ip: Failed to retrieve last reserved ip: open /var/lib/cni/networks/external/last_reserved_ip: no such file or directory
```

This fixes to not return an error when the file does not exist.

### CODE REVIEW

**Comment by ehazlett** [comment]
The test failure seems like a non code fail:

```
Bad response status from coveralls: 422 - {"message":"Couldn't find a repository matching this job.","error":true}
```

**Comment by squeed** [comment]
I'm not sure this is the right choice.
Rather, I think we should probably just return the unadorned error. That way the consumer can just call `os.IsNotExist` themselves.

**Comment by ehazlett** [comment]
Ah yes it seems it would be better to handle it here (https://github.com/containernetworking/cni/blob/master/plugins/ipam/host-local/backend/allocator/allocator.go#L255) and just create the directory instead of letting it log and continue.  I'll update.

**Comment by squeed** [comment]
Ah yes, that's what I meant. I didn't realize we were the consumer :-). Thanks.

**Comment by dcbw** [comment]
@ehazlett were you able to update the fix yet?

**Comment by ehazlett** [comment]
sorry for the delay!

updated -- thx!

**Comment by squeed** [comment]
You'll still need to edit `disk/backend.go#88` to return the original error.

**Comment by rosenhouse** [comment]
@ehazlett See above.  Also, could you add a unit test to cover this change?

**Comment by ehazlett** [comment]
@rosenhouse I've updated.  When trying to add a test it doesn't appear to run (I added a failing case to `master` but the test appears to be ignored as everything passes).  I even tried to run the tests direct based upon the test script but I get `no tests to run`.   I'm not famliar with ginkgo so this will take me a bit to dig through.

**Comment by ehazlett** [comment]
OK I think I found it.  I had to add a new test suite for `host-local`.  It appears none of those tests were running.

**Comment by ehazlett** [comment]
@rosenhouse OK I believe I've finished updating and have enabled / fixed the remaining failing tests.

**Comment by rosenhouse** [comment]
@ehazlett Awesome, thanks for getting this done!  (and amazing that none of those tests were running already).

👍 

other @containernetworking/cni-maintainers want to get this in before the release? (I'm tired of seeing this erroneous error message in my logs)

**Comment by squeed** [comment]
How embarrassing! Anyways, LGTM!

**Comment by ehazlett** [comment]
Thanks!

**Pull request merged**
