### PR TITLE
plugins/main/ptp: set the Sandbox property on the response

### PR DESCRIPTION
**Pull request by squeed**

### CODE REVIEW

**Comment by dcbw** [comment]
LGTM

**Comment by bboreham** [comment]
Please can you provide some context why this is needed.

**Comment by squeed** [comment]
PR 145 added passing back created interfaces, including host-side interfaces. We add the `sandbox` property to distinguish the two. This was missing in the `ptp` response.

**Comment by dcbw** [comment]
@bboreham I think I just missed adding that bit to the ptp plugin in #145.  I added it to the other main plugins, just not ptp.

**Pull request merged**
