### PR TITLE
Adding the Bonding CNI plugin as 3rd party plugin

### PR DESCRIPTION
**Pull request by rkamudhan**
- [Bonding CNI](https://github.com/Intel-Corp/bond-cni) provides a method for aggregating multiple network interfaces into a single logical "bonded" interface.
- Linx Bonding drivers provides various flavour of bonded interface depending on the mode (bonding policies), such as round robin, active aggregation according to the 802.3 ad specification
For more information on the bonding driver. Please refer to [kernel doc](https://www.kernel.org/doc/Documentation/networking/bonding.txt)

### CODE REVIEW

**Comment by rkamudhan** [comment]
Open source community project such as CNCF projects like CNI is used by the various segment of the Industries. It always cases that one segment use case or requirement doesn't make sense for other segments of the Industry. We can't say that CNCF projects support only one specific use cases. I can't argue with this statement, we end up in the rathole. 

In a technical point of view, Bonding is used for physical interfaces, it is supported in Linux driver. For example, readme file has SRIOV to provide that physical interfaces. In technical point, I don't feel there is need to comment whether it should not be a 3rd party plugin.

**Comment by matthewdupre** [comment]
@rkamudhan Sorry if I wasn't clear.  By "Can we get a slightly longer description", I meant can you make the descriptive text in this change more informative - I'm not asking you to justify inclusion.

I'm not trying to say it shouldn't be merged because it doesn't apply to every CNI user - just that I'd like the list to give readers a reasonable chance of realizing if this plugin is likely to be interesting to them or not.

**Comment by rkamudhan** [comment]
@matthewdupre Thanks for the clarification. I will update the readme file with more information

**Comment by rkamudhan** [comment]
@matthewdupre Update the readme to understand use case around failover and high availability network. Here link for more information on the use cases - https://www.howtoforge.com/tutorial/how-to-configure-high-availability-and-network-bonding-on-linux/

**Comment by matthewdupre** [comment]
I think the relationship between the physical and container interfaces is important - without SRIOV or something similarly it doesn't really make sense.

**Comment by rkamudhan** [comment]
Can you clarify the statement? Bonding is used to create logical interface out of two interfaces, It can run with or without SRIOV. You run bond cni with flannel using `delegate` option in flannel to connect to the overlay network.

**Comment by matthewdupre** [comment]
You could bond two veths, but it doesn't make much sense unless there are different physical interfaces backing them.

**Comment by rkamudhan** [comment]
Bonding CNI is generic, you can give the different physical interface to it.

**Comment by dcbw** [comment]
I'm find with the existing PR.

**Pull request merged**
