### PR TITLE
Fix handling of host-local IP address ranges

### PR DESCRIPTION
**Pull request by dcbw**
This fixes a couple of issues with RangeEnd/RangeStart and also has a different take on https://github.com/containernetworking/cni/pull/292.

### CODE REVIEW

**Comment by dcbw** [comment]
@freehan @containernetworking/cni-maintainers

**Comment by freehan** [comment]
LGTM. Thanks!

**Comment by jellonek** [comment]
LGTM

**Comment by rosenhouse** [comment]
This looks great, thanks for filling in so much test coverage.  Merging...

**Pull request merged**
