### PR TITLE
 Add poweron architecture ppc64le to travis build

### PR DESCRIPTION
**Pull request by asellappen**
This is part of the Ubuntu distribution for ppc64le. 
This helps us simplify testing later when distributions are re-building and re-releasing. For more info tag @gerrith3.

### CODE REVIEW

**Comment by gerrith3** [comment]
@asellappen You'll need to sign the DCO for this project.  Click on the failed DCO line above here for details.

**Comment by asellappen** [comment]
DCO has been signed off , Please help to review and merge the changes .

**Comment by squeed** [comment]
I think you've got this backwards; we want to cross-compile everything on amd64 *except* ppc64le, which we would like to build and test natively.

Check out how https://github.com/containernetworking/plugins/pull/539 does it - and use that approach.

**Comment by asellappen** [comment]
creating new pull requests as this got many commits

**Pull request closed without merging**
