### PR TITLE
Macvtap plugin

### PR DESCRIPTION
**Pull request by rmohr**
Code to discuss #315.

### CODE REVIEW

**Comment by rosenhouse** [comment]
Hi @rmohr: thanks for taking the time to put this together.  It looks really interesting and it's great to see new types of CNI plugins!

I'd point you to our [Acceptance Policy](https://github.com/containernetworking/cni/blob/master/CONTRIBUTING.md#acceptance-policy).  In particular:

- We generally [encourage new plugins to be developed in separate repositories] (https://github.com/containernetworking/cni/blob/master/CONTRIBUTING.md#3rd-party-plugins)

- We expect all new code to be covered by tests

**Comment by leodotcloud** [comment]
@rosenhouse This is a generic plugin similar to the already available macvlan/ipvlan plugins. It's not a third party plugin.

Or does it makes sense to separate the generic plugins of CNI into a separate repo to keep the SPEC and core functionality in the cni repo?

**Comment by squeed** [comment]
Reviving this:
1) Are any spec changes still proposed?
2) There may be a use for a kvm hierarchy in the `plugins` repository. If you like, you may wish to open a PR there.

**Comment by rosenhouse** [comment]
All CNI plugins maintained by the CNI team have moved to https://github.com/containernetworking/plugins

If you'd still like to contribute this to the CNI project, please open a new PR there, and we can discuss.  Closing this one.

**Pull request closed without merging**
