### PR TITLE
introduce hybridnet to thrid-party plugins

### PR DESCRIPTION
**Pull request by mars1024**
link to [hybridnet](https://github.com/alibaba/hybridnet)

Signed-off-by: Bruce Ma <brucema19901024@gmail.com>

### CODE REVIEW

**Review by matthewdupre — COMMENTED** [review]
What does this mean, from the perspective of someone looking to compare CNI plugins?  I think it might be clearer for people if they knew that containers could be attached to either the underlay or the overlay.

**Comment by mars1024** [comment]
> What does this mean, from the perspective of someone looking to compare CNI plugins? I think it might be clearer for people if they knew that containers could be attached to either the underlay or the overlay.

Yes, from the perspective of usage, one container can only choose to be attached to underlay or overlay, but `hybrid-lay` here means overlay pods and underlay pods will have complete bidirectional network connectivity on node level in one cluster, even among multi clusters. This seems a creative feature compared to other 3rd party plugins.

**Comment by matthewdupre** [comment]
Could you add some of that to the comment please @mars1024 (admittedly it's a challenge to balance with brevity)?  People should be able to get an idea for whether they'd be interested just from reading the list.

**Comment by mars1024** [comment]
@matthewdupre Updated the comment, more words but more comprehensible :)

**Comment by mars1024** [comment]
friendly ping @matthewdupre @dcbw , any comments on this?

**Comment by mars1024** [comment]
> @mars1024 could we reword slightly to:
> 
> `a CNI plugin designed for hybrid clouds which provides both overlay and underlay networking for containers in one or more clusters. Overlay and underlay containers can run on the same node and have cluster-wide bidirectional network connectivity.`

@dcbw  Of course and I've already reworded this. Thanks!

**Pull request closed without merging**
