### PR TITLE
docs: correct the extension name of the configuration file

### PR DESCRIPTION
**Pull request by DrmagicE**

### CODE REVIEW

**Review by mars1024 — CHANGES_REQUESTED** [review]
Actually `LoadConfList` used by `cnitool` will search files with extension `.conflist` firstly then fall through to `.conf` and `.json`, so this should be clear cut in documents.

**Comment by DrmagicE** [comment]
Oh, I see... I was putting a list configuration into a  file with `.json` extension and then I got the "error parsing configuration: missing 'type'" error message. 
Now I realize the `.json` or `.conf` extension is for single plugin, and `.conflist` is for plugin chain.  I think it would be more clear if we mention this in the document.

**Comment by DrmagicE** [comment]
@mars1024 Hi, I have revised the doc to add more details. Would you please take a look？

**Comment by dcbw** [comment]
Thanks!

**Pull request merged**
