### PR TITLE
V0.2.2 + back-ported [plugins/bridge: clean masquerading rules]

### PR DESCRIPTION
**Pull request by tmrts**
Backports #195 to v0.2.2, which is a fix for iptable rule leaks in rkt (See rkt#2565)

### CODE REVIEW

**Comment by iaguis** [comment]
I think we need https://github.com/containernetworking/cni/pull/177 too to fix https://github.com/coreos/rkt/issues/1765 for the nspawn flavor.

**Comment by tmrts** [comment]
@iaguis Alright I'll turn this into 'v0.2.3', do you have any more fixes in mind @jonboulle @alban?

**Comment by jonboulle** [comment]
nope, not that I can think of

**Comment by jonboulle** [comment]
I think @steveeJ had concerns about the https://github.com/containernetworking/cni/pull/177 patch though..

**Comment by jonboulle** [comment]
Let's hold off on that one for now. #2565 is a lot more critical.

**Comment by jonboulle** [comment]
@tmrts github is confusing me - is this against v0.2.2, even though it says "tmrts  wants to merge 6 commits into containernetworking:master from tmrts:v0.2.2"?

**Comment by tmrts** [comment]
@jonboulle I specifically selected a new branch, I'll make sure it's the case before merging

**Comment by tmrts** [comment]
@jonboulle as it turns out, I can't even push a PR to a non-existant without write access.

**Comment by steveeJ** [comment]
Closing in favor of #203

**Pull request closed without merging**
