### PR TITLE
plugins: moved to containernetworking/plugins

### PR DESCRIPTION
**Pull request by dcbw**
@containernetworking/cni-maintainers

### CODE REVIEW

**Comment by squeed** [comment]
Neat. +1

**Comment by feiskyer** [comment]
+1. LGTM

**Comment by dcbw** [comment]
@squeed repushed with updated libcni legacy testcase

**Comment by squeed** [comment]
Delightful. A joy and a treasure.
(Needs one more maintainer LGTM)

**Comment by squeed** [comment]
FWIW, I have a followup PR moving most of `pkg/...` to plugins.

**Pull request merged**
