### PR TITLE
Log out the plugin name on ADD/DEL failure.

### PR DESCRIPTION
**Pull request by fasaxc**
Makes it easier to diagnose conf lists when one plugin fails.

### CODE REVIEW

**Comment by mars1024** [comment]
ptal at the failed unit tests

**Comment by fasaxc** [comment]
@mars1024 done, thanks.

**Review by bboreham — APPROVED** [review]
LGTM - we need to announce in the release notes that the type signature of these errors has changed, but arguably anyone calling this code should be ready to deal with that.

**Pull request merged**
