### PR TITLE
Update of netlink version

### PR DESCRIPTION
**Pull request by lukasredynk**
This is required for
https://github.com/containernetworking/cni/issues/251 because current version of
netlink in vendor doesn't support creating tap devices.

### CODE REVIEW

**Comment by pskrzyns** [comment]
cc @steveeJ

**Comment by jellonek** [comment]
Changes only in vendored library and checks seems passing ok, so LGTM.

**Comment by jjlakis** [comment]
LGTM. It can be safely merged regardless of https://github.com/containernetworking/cni/issues/251 result. @steveeJ Any doubts?

**Comment by rosenhouse** [comment]
👍 @containernetworking/cni-maintainers anyone else want to give the second 👍

**Comment by tomdee** [comment]
:+1: LGTM - merging.

**Pull request merged**
