### PR TITLE
Adding reference to Azure CNI as 3rd party plugin in README

### PR DESCRIPTION
**Pull request by chandanAggarwal**
Adding reference to Azure CNI in the README.

### CODE REVIEW

**Comment by chandanAggarwal** [comment]
@squeed , @dcbw , can you please help in getting this PR merged. Thanks a lot !

**Review by bboreham — APPROVED** [review]
lgtm

**Comment by chandanAggarwal** [comment]
@bboreham  thanks for approving, can you please also merge the PR, I don't have rights to do that.

**Review by mars1024 — APPROVED** [review]
/lgtm

**Pull request merged**
