### PR TITLE
Add go.mod

### PR DESCRIPTION
**Pull request by sargun**

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks for the PR.  Unfortunately it seems to have broken tests - would you be able to make `test.sh` run and update the PR?

Also I normally expect to see a `go.sum` file alongside a `go.mod`.

**Comment by squeed** [comment]
hey @sargun - do you have time to work on this?

**Comment by sargun** [comment]
Sure, I'll try to get to it later this week.

**Comment by mccv1r0** [comment]
Taken care of by https://github.com/containernetworking/cni/pull/774

**Pull request closed without merging**
