### PR TITLE
update NetConf.DNS's json tag to omitempty

### PR DESCRIPTION
**Pull request by cyclinder**
Fixes https://github.com/containernetworking/cni/issues/1006

### CODE REVIEW

**Comment by cyclinder** [comment]
Thanks for the tip. Updated.

**Comment by cyclinder** [comment]
Hi @dcbw, I found `IPAM` and `DNS` fields are also tagged with `omitempty`, but this has no effect. 

```
type NetConf struct {
	CNIVersion string `json:"cniVersion,omitempty"`
	IPAM         IPAM            `json:"ipam,omitempty"`
	DNS          DNS             `json:"dns,omitempty"`
}

type IPAM struct {
	Type string `json:"type,omitempty"`
}

type Test struct {
	Name string `json:"name,omitempty"`
}

func main(){
     	t := &test{
	    CNIVersion: "test",
	}

	bytes,err := json.Marshal(t)
	if err != nil {
		log.Fatalln(err)
	}

	log.Println(string(bytes))
}

#cyclinder~ go run main.go
2023/07/11 11:19:00 {"ipam":{},"dns":{},"cniVersion":"test"}
```

We should make struct to a pointer. Pointers have obvious "empty" values: `nil`.

```
type NetConf struct {
	CNIVersion string `json:"cniVersion,omitempty"`
	IPAM         *IPAM            `json:"ipam,omitempty"`
	DNS          *DNS             `json:"dns,omitempty"`
}

type IPAM struct {
	Type string `json:"type,omitempty"`
}

type Test struct {
	Name string `json:"name,omitempty"`
}

func main(){
     	t := &test{
	    CNIVersion: "test",
	}

	bytes,err := json.Marshal(t)
	if err != nil {
		log.Fatalln(err)
	}

	log.Println(string(bytes))
}

#cyclinder~ go run main.go
2023/07/11 11:21:00 {"cniVersion":"test"}
```

**Comment by cyclinder** [comment]
@dcbw Hi, Could you take a look? Can we set `IPAM` and `DNS` as pointers?

**Comment by cyclinder** [comment]
Hey @squeed, Could you please take a look? Thanks.

**Comment by s1061123** [comment]
I suppose we also need to change DNS in Result (at least 1.0.0) to pointer as well as NetConf if we change NetConf's DNS type. What do you think about that?

**Comment by s1061123** [comment]
I will cherry-pick your change and create another PR to care about both (NetConf + Result). Please let me know if you mind it. Thanks!

**Comment by s1061123** [comment]
Files https://github.com/containernetworking/cni/pull/1035 with your commit (as cherry-pick).

**Comment by cyclinder** [comment]
Sorry for the delay @s1061123  due to busy with working :>

> Please let me know if you mind it. Thanks!

It doesn't matter, you are welcome.

**Comment by s1061123** [comment]
Closed because https://github.com/containernetworking/cni/pull/1039 fixes this issue.

**Pull request closed without merging**
