### PR TITLE
Add Project Antrea in CNI list

### PR DESCRIPTION
**Pull request by yasensim**

### CODE REVIEW

**Comment by bboreham** [comment]
Any particular reason why this takes the 2nd spot?

**Comment by yasensim** [comment]
no real reason. Usually it is alphabetical order on the other lists. I don't mind reordering it. just let me know where to put it and I will do.

**Comment by mars1024** [comment]
I think appending is better than inserting. Actually the order is only based on time.

**Comment by yasensim** [comment]
@mars1024  done!

**Comment by mars1024** [comment]
> @mars1024 done!

Thanks, lgtm!

**Pull request merged**
