### PR TITLE
Remove invalid 404 links

### PR DESCRIPTION
**Pull request by xichengliudui**
I checked the other branches and did not find this file, so I think this file should have been deleted.

### CODE REVIEW

**Comment by bboreham** [comment]
I think what happened is the `host-local` plugin moved to another repository. 
 The link should be https://github.com/containernetworking/plugins/tree/master/plugins/ipam/host-local#supported-arguments

**Comment by xichengliudui** [comment]
@bboreham  Thank you for your reminding. I have modified it.

**Comment by bboreham** [comment]
Thanks.  Can you squash the two commits into one please.

**Pull request closed without merging**
