### PR TITLE
README: grammatical corrections

### PR DESCRIPTION
**Pull request by leecalcote**
README: grammatical corrections - two commas and a hyphen

To improve legibility and understanding, I added two commas and a hyphen as grammatical corrections to the README.md

### CODE REVIEW

**Comment by steveeJ** [comment]
Please adjust the commit message(s) to conform to https://github.com/containernetworking/cni/blob/master/CONTRIBUTING.md#format-of-the-commit-message, thanks a lot!

**Comment by leecalcote** [comment]
Sure, @steveeJ. I updated the subject line to include the _what_ and the commit message body to include the _why_. I hope this helps.

**Comment by steveeJ** [comment]
@leecalcote I know this is almost not worth discussing for such a small change but, we're trying to have a clean git log to be able to track changes. If you could add the _subsystem:_ to your commit which would be _README:_ in this case, that would be excellent, thanks!

**Comment by leecalcote** [comment]
@steveeJ you bet. I updated. Let me know if it doesn't quite look right.

**Comment by steveeJ** [comment]
@leecalcote last piece missing: commit message title ;)

**Comment by leecalcote** [comment]
@steveeJ Sure, will update. This may seem a bit silly - I'm not entirely sure where to put the title or what its specific format should be. I'm editing via my browser on github.com (in case that makes a difference). 

Of what I see in the [contrib guidelines](https://github.com/containernetworking/cni/blob/master/CONTRIBUTING.md#format-of-the-commit-message), I _think_ I have used that format:

screen shot 2016-06-14 at 6 41 00 am

I'm happy to update the PR with an appropriately formatted title. If you've an example title, I can use that. :)

**Comment by steveeJ** [comment]
@leecalcote no worries, thanks for pushing through this pain ;) I'm talking about the git commit title which you can also see in your local repository using `git log`, or here https://github.com/containernetworking/cni/pull/246/commits. You can change the commit title e.g. using `git commit --amend` if your PR branch is checked out.

**Pull request merged**
