### PR TITLE
Add route attributes - MTU, AdvMSS, Priority

### PR DESCRIPTION
**Pull request by alopintsev**
Extend route attributes to make route selection available based on route priority and enable per-route MTU settings.
It's will be helpfull in multi-CNI environment, and networks, that support jumbo-frame.

Fixes: #1004

### CODE REVIEW

**Comment by alopintsev** [comment]
> @alopintsev looks reasonable. However, we will need to update the specification as well, as these are defined types. Thanks!

I've made changes in specification, would you mind to check it?

**Review by squeed — APPROVED** [review]

**Review by squeed — APPROVED** [review]
Looks good, thanks!

**Comment by squeed** [comment]
FYI @aojea / @Joffref, who had also looked at this.

**Comment by aojea** [comment]
LGTM

**Pull request merged**
