### PR TITLE
invoke: fix typo (opensbd -> openbsd)

### PR DESCRIPTION
**Pull request by ajacoutot**

### CODE REVIEW

**Comment by ajacoutot** [comment]
Thanks @bboreham , could someone with write access merge this please?

**Comment by bboreham** [comment]
I am following the process at https://github.com/containernetworking/cni/blob/master/CONTRIBUTING.md#acceptance-policy, ie one more approval is needed.

**Comment by ajacoutot** [comment]
> I am following the process at https://github.com/containernetworking/cni/blob/master/CONTRIBUTING.md#acceptance-policy, ie one more approval is needed.

Ah right sorry :innocent:

**Comment by dcbw** [comment]
LGTM

**Pull request merged**
